rent crud operations
ToStefan/hybrid-it-lib pull request #4
Opened 2019-05-27 09:22 UTC by ToStefan

2019-05-27 09:43 UTC, babicmilan requested changes

2019-05-27 09:43 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +    public List<RentedBookDTO> getMostRented() {
Definitely go for an SQL query. It is much more performant and will simplify the logic by removing the need to sort and limit the elements.

2019-05-27 09:43 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +
Generally avoid having methods this big. They are hard to read and make changes. Each method should have only one responsibility. In this case the method should splitted into a couple of private methods, for instance fetch(), sort() and map()

2019-05-27 09:43 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/web/controller/RentController.java
> +    @GetMapping
The count of rents can grow to a quite large number, consider using paging.

2019-05-27 09:54 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +            int count = bookCounter.containsKey(r.getBookId()) ? bookCounter.get(r.getBookId()) : 0;
could use Collectors.counting
something like 
 Map<Book, Long> countedBooks = bookRentalRepository.findAll().stream()
                .collect(Collectors.groupingBy(Rent::getBook, Collectors.counting()))

2019-05-27 12:10 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +        List<RentDTO> rentsDTOs = rentMapper.toDTO(rentRepository.findAll());
potentially low performant operation, If the number of rents is a high number,
Consider adding an addtional field in rent table (returnByDate for example) which could be calculated in moment of renting a book. Then finding overdue books could be done by JPA query where current_date is after returnByDate

2019-05-28 11:47 UTC, babicmilan requested changes

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/exception/EntityNotFoundException.java
> +
Add a constructor with a string parameter so you can send some more info about the entity which is not found.

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/exception/ExceptionController.java
> +        error.setErrorMessage("Entity not found!");
Set the error message from the EntityNotFoundException instead of "Entity not found!"

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException()));
Here set the error message, that the book entity is not found and by which id was it searched for in the DB.

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException());
same here

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new));
same

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/UserServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new));
s

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/UserServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new));
same

2019-05-28 11:47 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/UserServiceImpl.java
> +                .orElseThrow(EntityNotFoundException::new);
same

2019-05-28 11:49 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/exception/ExceptionController.java
> +@ControllerAdvice
https://stackoverflow.com/questions/43124391/restcontrolleradvice-vs-controlleradvice

2019-05-28 12:29 UTC, merged