Security
ToStefan/hybrid-it-lib pull request #5
Opened 2019-05-29 12:42 UTC by ToStefan

2019-05-29 13:52 UTC, mspavkovic approved these changes

2019-05-29 14:00 UTC, nemanja-blagojevic-valcon commented on src/main/java/hybrid/it/internship/library/config/SecurityConfig.java
> +    @Autowired
Use constructor wiring instead

2019-05-29 14:00 UTC, nemanja-blagojevic-valcon commented on src/main/java/hybrid/it/internship/library/security/AuthenticationEntryPoint.java
> +        PrintWriter writer = response.getWriter();
Use slf4J instead..

2019-05-29 14:00 UTC, nemanja-blagojevic-valcon commented on src/main/java/hybrid/it/internship/library/security/UserPrincipal.java
> +    public UserPrincipal(String username, String password, List<GrantedAuthority> roles) {
put constructor on top

2019-05-29 14:00 UTC, nemanjab-hybridit commented on src/main/java/hybrid/it/internship/library/service/impl/UserServiceImpl.java
> +    @Bean
Use classical wiring..

2019-05-30 09:00 UTC, babicmilan requested changes

2019-05-30 09:00 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/security/UserPrincipal.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
use @Slf4j provided by lombok

2019-05-30 09:00 UTC, babicmilan commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
same

2019-05-30 09:06 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/LibraryApplication.java
> +import org.slf4j.Logger;
remove not used imports

2019-05-30 09:08 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/security/UserPrincipal.java
>  public class UserPrincipal implements UserDetails {
Use @Slf4j lombok annotation for logging https://projectlombok.org/features/log

2019-05-30 09:09 UTC, mspavkovic commented on src/main/java/hybrid/it/internship/library/service/impl/RentServiceImpl.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
same as above

2019-05-30 11:47 UTC, nemanja-blagojevic-valcon approved these changes

2019-05-30 11:47 UTC, mspavkovic approved these changes

2019-05-30 11:48 UTC, merged